### PR TITLE
Create mosfet-switch1.ipynb

### PR DESCRIPTION
**Pull request by OIEIEIO**
how to use in colab

### CODE REVIEW

**Comment by mph-** [comment]
This looks good thanks, but why is folium required?

**Comment by OIEIEIO** [comment]
Oops I missed that, your correct, folium is not required, thanks for pointing that out. I was working on an expanded version of the basic notebook and forgot to remove it. Updated now, removed from the readme and the mosfet-switch notebook.

**Comment by OIEIEIO** [comment]
> This looks good thanks, but why is folium required?
Oops I missed that, your correct, folium is not required, thanks for pointing that out. I was working on an expanded version of the basic notebook and forgot to remove it. Updated now, removed from the readme and the mosfet-switch notebook.

**Comment by OIEIEIO** [comment]
> This looks good thanks, but why is folium required?

Oops I missed that, you're correct, folium is not required, thanks for pointing that out. I was working on an expanded version of the basic notebook and forgot to remove it. Updated now, removed from the readme and the mosfet-switch notebook.

**Pull request merged**
